/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import Conexion.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brant
 */
public class pnlInventario extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicioo
     */
    public pnlInventario() {
        initComponents();
        btnNuevo.setVisible(true);
        btnRegistrar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);

        //Llenar cobobox
        Conexion conexion = new Conexion();
        //Conexion
        Statement st;
        ResultSet rs;
        
        cbxProveedor.removeAllItems();
        ArrayList<String> lista = new ArrayList<String>();

        try {
            st = conexion.con.createStatement();
            rs = st.executeQuery("SELECT concat(nombreProveedor,' ',apellidoProveedor) AS 'Nombres' FROM sistemamg.proveedor;");
            lista.add("--Seleccione el proveedor--");
            while (rs.next()) {
                lista.add(rs.getString("Nombres"));
            }

        } catch (Exception e) {
            System.out.println("Error lista proveedores");
        }
        
        
        for(int i = 0; i<lista.size();i++){
        
        cbxProveedor.addItem(lista.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloInventario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        btnCargar = new javax.swing.JButton();
        lblBuscarInventario = new javax.swing.JLabel();
        cboBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTituloInventario2 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtApellidoProveedor = new javax.swing.JTextField();
        lblTalla = new javax.swing.JLabel();
        txtCedulaProveedor = new javax.swing.JTextField();
        lblInicial = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        lblPrecioUnitario = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblId = new java.awt.Label();
        txtDiasPlazo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloInventario.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lblTituloInventario.setText("Inventario");

        tblInventario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Talla", "Cantidad inicial", "Stock", "Precio unitario", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.setRowHeight(30);
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        btnCargar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        lblBuscarInventario.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lblBuscarInventario.setText("Buscar");

        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Buscar por--", "Código", "Descripción", "Talla", "Proveedor" }));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboBuscar, 0, 177, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblBuscarInventario))
                    .addComponent(txtBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCargar)
                        .addGap(23, 23, 23)))
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(lblTituloInventario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBuscarInventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(btnCargar)
                        .addGap(66, 66, 66))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloInventario2.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lblTituloInventario2.setText("Registrar en Inventario");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCodigo.setText("Código:");

        txtNombreProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDescripcion.setText("Descripción:");

        txtApellidoProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtApellidoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoProveedorActionPerformed(evt);
            }
        });

        lblTalla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTalla.setText("Talla:");

        txtCedulaProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInicial.setText("Cantidad inicial:");

        txtNumeroCuenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblStock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStock.setText("Stock:");

        txtTelefonoProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblPrecioUnitario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPrecioUnitario.setText("Precio unitario:");

        lblProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProveedor.setText("Proveedor:");

        cbxProveedor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SeleccioneProveedor--" }));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(204, 0, 0));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMensaje.setInheritsPopupMenu(false);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblId.setForeground(new java.awt.Color(255, 255, 255));

        txtDiasPlazo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(lblTituloInventario2)
                        .addGap(17, 17, 17)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPrecioUnitario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefonoProveedor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTalla)
                                .addGap(33, 33, 33)
                                .addComponent(txtCedulaProveedor))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblInicial)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStock)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(184, 184, 184))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloInventario2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtApellidoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTalla)
                    .addComponent(txtCedulaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInicial)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock)
                    .addComponent(txtDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioUnitario)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProveedor)
                    .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(183, 183, 183)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        ControladorProveedor proveedor = new ControladorProveedor(txtNombreProveedor.getText(), txtApellidoProveedor.getText(),
                txtCedulaProveedor.getText(), txtNumeroCuenta.getText(), txtDiasPlazo.getText(), txtTelefonoProveedor.getText(),
                cbxProveedor.getSelectedItem().toString(), txtBanco.getText(), lblId.getText().toString());

        if (proveedor.verificacion(false).length() == 0) {
            JOptionPane.showMessageDialog(null, "Registrado con éxito");
            limpiarCampos();
            cargarTabla();
        } else {
            lblMensaje.setText(proveedor.verificacion(false));
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtApellidoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoProveedorActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        cargarTabla();


    }//GEN-LAST:event_btnCargarActionPerformed

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked

        lblTituloInventario2.setText("Modificar/Eliminar Proveedor");

        btnNuevo.setVisible(true);
        btnRegistrar.setVisible(false);
        btnModificar.setVisible(true);
        btnEliminar.setVisible(true);

        int id = 0;

        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion conexion = new Conexion();

            int fila = tblInventario.getSelectedRow();
            String cedula = tblInventario.getValueAt(fila, 2).toString();

            ps = conexion.con.prepareStatement("SELECT idProveedor,nombreProveedor,apellidoProveedor,cedulaRucProveedor,numeroCuenta,diasPlazo,numeroTelefono,reciboProveedor,bancoProveedor FROM sistemamg.proveedor WHERE cedulaRucProveedor=?");
            ps.setString(1, cedula);
            rs = ps.executeQuery();

            while (rs.next()) {
                id = rs.getInt("idProveedor");
                lblId.setText(String.valueOf(id));
                txtNombreProveedor.setText(rs.getString("nombreProveedor"));
                txtApellidoProveedor.setText(rs.getString("apellidoProveedor"));
                txtCedulaProveedor.setText(rs.getString("cedulaRucProveedor"));
                txtNumeroCuenta.setText(rs.getString("numeroCuenta"));
                txtDiasPlazo.setText(rs.getString("diasPlazo"));
                txtTelefonoProveedor.setText(rs.getString("numeroTelefono"));
                txtBanco.setText(rs.getString("bancoProveedor"));
                cbxProveedor.setSelectedItem(rs.getString("reciboProveedor"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

        System.out.println(id);


    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        lblTituloInventario2.setText("Registrar nuevo proveedor");

        ControladorProveedor proveedor = new ControladorProveedor(txtNombreProveedor.getText(), txtApellidoProveedor.getText(),
                txtCedulaProveedor.getText(), txtNumeroCuenta.getText(), txtDiasPlazo.getText(), txtTelefonoProveedor.getText(),
                cbxProveedor.getSelectedItem().toString(), txtBanco.getText(), lblId.getText().toString());

        if (proveedor.verificacion(true).length() == 0) {
            JOptionPane.showMessageDialog(null, "Modificado con éxito");
            limpiarCampos();
            cargarTabla();
        } else {
            lblMensaje.setText(proveedor.verificacion(true));
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        PreparedStatement ps = null;
        try {

            Conexion conexion = new Conexion();

            ps = conexion.con.prepareStatement("DELETE FROM sistemamg.proveedor WHERE idProveedor=" + lblId.getText().toString());
            ps.execute();

            JOptionPane.showMessageDialog(null, "Proveedor Eliminado");
            cargarTabla();
            limpiarCampos();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar Proveedor");
            System.out.println(ex.toString());
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        limpiarCampos();
        btnNuevo.setVisible(true);
        btnRegistrar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla() {
        try {

            DefaultTableModel modelo = new DefaultTableModel();
            tblInventario.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conexion = new Conexion();
            String sql = "SELECT nombreProveedor,apellidoProveedor,cedulaRucProveedor,numeroCuenta,diasPlazo,numeroTelefono,reciboProveedor, bancoProveedor FROM sistemamg.proveedor";
            ps = conexion.con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Cédula/RUC");
            modelo.addColumn("Número cuenta");
            modelo.addColumn("Días plazo");
            modelo.addColumn("Número teléfono");
            modelo.addColumn("Recibo");
            modelo.addColumn("Banco");

            while (rs.next()) {

                Object[] filas = new Object[cantidadColumnas];

                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }

                modelo.addRow(filas);

            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }

    }

    private void limpiarCampos() {

        lblTituloInventario2.setText("Registrar nuevo proveedor");
        txtNombreProveedor.setText("");
        txtApellidoProveedor.setText("");
        txtCedulaProveedor.setText("");
        txtNumeroCuenta.setText("");
        txtDiasPlazo.setText("");
        txtTelefonoProveedor.setText("");
        cbxProveedor.setSelectedIndex(0);
        txtBanco.setText("");

        lblMensaje.setText("");
        lblMensaje.setForeground(Color.red);
        btnNuevo.setVisible(true);
        btnRegistrar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        lblId.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarInventario;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private java.awt.Label lblId;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPrecioUnitario;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTituloInventario;
    private javax.swing.JLabel lblTituloInventario2;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtApellidoProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedulaProveedor;
    private javax.swing.JTextField txtDiasPlazo;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
