/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemazapatos;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import paneles.CambiaPaneles;
import paneles.pnlConsultas;
import paneles.pnlEmpleados;
import paneles.pnlInicio;
import paneles.pnlInventario;
import paneles.pnlPedidos;
import paneles.pnlProveedores;
import paneles.pnlRegistrarVenta;
import paneles.pnlSalir;

/**
 *
 * @author brant
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.setTitle("Sistema MG");
        //Cambiar Icono
        setIconImage(new ImageIcon(getClass().getResource("/img/logo1.png")).getImage());
        //Centrar Frame

        //Contraer menú
        this.setLocationRelativeTo(this);
        this.btnInicio.setSelected(true);
        new CambiaPaneles(pnlPrincipal, new pnlInicio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rSButton6 = new rsbutton.RSButton();
        pnlGeneral = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new rsbutton.RSButton();
        btnRegVenta = new rsbutton.RSButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEmpleados = new rsbutton.RSButton();
        btnSalir = new rsbutton.RSButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnInventario = new rsbutton.RSButton();
        btnProveedores = new rsbutton.RSButton();
        btnConsultas = new rsbutton.RSButton();
        btnPedidos = new rsbutton.RSButton();
        pnlBarra = new javax.swing.JPanel();
        btnMenu1 = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        rSButton6.setBackground(new java.awt.Color(0, 102, 204));
        rSButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        rSButton6.setText("Consultas");
        rSButton6.setActionCommand("CONSULTAS");
        rSButton6.setColorHover(new java.awt.Color(0, 51, 153));
        rSButton6.setColorNormal(new java.awt.Color(0, 102, 204));
        rSButton6.setColorPressed(new java.awt.Color(0, 153, 204));
        rSButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButton6.setIconTextGap(2);
        rSButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGeneral.setBackground(new java.awt.Color(255, 255, 255));
        pnlGeneral.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PRINCIPAL");

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnInicio.setText("   Inicio");
        btnInicio.setColorHover(new java.awt.Color(74, 20, 140));
        btnInicio.setColorNormal(new java.awt.Color(106, 27, 154));
        btnInicio.setColorPressed(new java.awt.Color(142, 36, 170));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnInicio.setIconTextGap(2);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioMousePressed(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnRegVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        btnRegVenta.setText("Registrar Venta");
        btnRegVenta.setColorHover(new java.awt.Color(74, 20, 140));
        btnRegVenta.setColorNormal(new java.awt.Color(106, 27, 154));
        btnRegVenta.setColorPressed(new java.awt.Color(142, 36, 170));
        btnRegVenta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegVenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegVenta.setIconTextGap(2);
        btnRegVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegVentaMousePressed(evt);
            }
        });
        btnRegVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("CUENTA");

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Empleado.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setColorHover(new java.awt.Color(74, 20, 140));
        btnEmpleados.setColorNormal(new java.awt.Color(106, 27, 154));
        btnEmpleados.setColorPressed(new java.awt.Color(142, 36, 170));
        btnEmpleados.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEmpleados.setIconTextGap(2);
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadosMousePressed(evt);
            }
        });
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.setColorHover(new java.awt.Color(74, 20, 140));
        btnSalir.setColorNormal(new java.awt.Color(106, 27, 154));
        btnSalir.setColorPressed(new java.awt.Color(142, 36, 170));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalir.setIconTextGap(2);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("GERENCIA");

        btnInventario.setBackground(new java.awt.Color(106, 27, 154));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invent.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setColorHover(new java.awt.Color(74, 20, 140));
        btnInventario.setColorNormal(new java.awt.Color(106, 27, 154));
        btnInventario.setColorPressed(new java.awt.Color(142, 36, 170));
        btnInventario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInventario.setIconTextGap(2);
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInventarioMousePressed(evt);
            }
        });
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedor.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setColorHover(new java.awt.Color(74, 20, 140));
        btnProveedores.setColorNormal(new java.awt.Color(106, 27, 154));
        btnProveedores.setColorPressed(new java.awt.Color(142, 36, 170));
        btnProveedores.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProveedores.setIconTextGap(2);
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedoresMousePressed(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultas.png"))); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.setColorHover(new java.awt.Color(74, 20, 140));
        btnConsultas.setColorNormal(new java.awt.Color(106, 27, 154));
        btnConsultas.setColorPressed(new java.awt.Color(142, 36, 170));
        btnConsultas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnConsultas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultas.setIconTextGap(2);
        btnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultasMousePressed(evt);
            }
        });
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(106, 27, 154));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setColorHover(new java.awt.Color(74, 20, 140));
        btnPedidos.setColorNormal(new java.awt.Color(106, 27, 154));
        btnPedidos.setColorPressed(new java.awt.Color(142, 36, 170));
        btnPedidos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPedidos.setIconTextGap(2);
        btnPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPedidosMousePressed(evt);
            }
        });
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        pnlGeneral.add(pnlMenu, gridBagConstraints);

        pnlBarra.setBackground(new java.awt.Color(106, 27, 154));

        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu1.setToolTipText("");
        btnMenu1.setBorder(null);
        btnMenu1.setContentAreaFilled(false);
        btnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1077, Short.MAX_VALUE))
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        pnlGeneral.add(pnlBarra, gridBagConstraints);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(700, 300));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );

        pnlPrincipal.add(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        pnlGeneral.add(pnlPrincipal, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVentaActionPerformed
        new CambiaPaneles(pnlPrincipal, new pnlRegistrarVenta());
        if (this.btnRegVenta.isSelected()) {
            this.btnRegVenta.setColorNormal(new Color(142, 36, 170));
            this.btnRegVenta.setColorHover(new Color(142, 36, 170));
            this.btnRegVenta.setColorPressed(new Color(142, 36, 170));

            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));

            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));
            
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));

            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));

            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(74, 20, 140));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));
        }

    }//GEN-LAST:event_btnRegVentaActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        new CambiaPaneles(pnlPrincipal, new pnlInventario());
        if (this.btnInventario.isSelected()) {
            this.btnInventario.setColorNormal(new Color(142, 36, 170));
            this.btnInventario.setColorHover(new Color(142, 36, 170));
            this.btnInventario.setColorPressed(new Color(142, 36, 170));

            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));

            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));
            
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));

            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));

            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(74, 20, 140));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));
        }

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void rSButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton6ActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        new CambiaPaneles(pnlPrincipal, new pnlProveedores());
        if (this.btnProveedores.isSelected()) {
            this.btnProveedores.setColorNormal(new Color(142, 36, 170));
            this.btnProveedores.setColorHover(new Color(142, 36, 170));
            this.btnProveedores.setColorPressed(new Color(142, 36, 170));

            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));

            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));
            
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));

            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));

            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(74, 20, 140));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));
        }

    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        new CambiaPaneles(pnlPrincipal, new pnlEmpleados());
        if (this.btnEmpleados.isSelected()) {
            this.btnEmpleados.setColorNormal(new Color(142, 36, 170));
            this.btnEmpleados.setColorHover(new Color(142, 36, 170));
            this.btnEmpleados.setColorPressed(new Color(142, 36, 170));

            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));

            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));
            
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));

            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));

            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(74, 20, 140));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));
        }


    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        Login login = new Login();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed

        int posicion = this.pnlMenu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -251, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(-250, 0, 2, 2, pnlMenu);
        }


    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new CambiaPaneles(pnlPrincipal, new pnlInicio());
        if (this.btnInicio.isSelected()) {
            this.btnInicio.setColorNormal(new Color(142, 36, 170));
            this.btnInicio.setColorHover(new Color(142, 36, 170));
            this.btnInicio.setColorPressed(new Color(142, 36, 170));

            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));

            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));
            
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));

            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));

            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(74, 20, 140));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));
        }

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMousePressed

        this.btnInicio.setSelected(true);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(false);


    }//GEN-LAST:event_btnInicioMousePressed

    private void btnRegVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegVentaMousePressed

        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(true);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(false);

    }//GEN-LAST:event_btnRegVentaMousePressed

    private void btnInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMousePressed

        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(true);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(false);

    }//GEN-LAST:event_btnInventarioMousePressed

    private void btnProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMousePressed

        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(true);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(false);

    }//GEN-LAST:event_btnProveedoresMousePressed

    private void btnEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMousePressed

        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(true);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(false);

    }//GEN-LAST:event_btnEmpleadosMousePressed

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed

        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(true);
        this.btnConsultas.setSelected(false);

    }//GEN-LAST:event_btnSalirMousePressed

    private void btnConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasMousePressed

        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(false);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(true);

    }//GEN-LAST:event_btnConsultasMousePressed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed

        new CambiaPaneles(pnlPrincipal, new pnlConsultas());
        if (this.btnConsultas.isSelected()) {
            this.btnConsultas.setColorNormal(new Color(142, 36, 170));
            this.btnConsultas.setColorHover(new Color(142, 36, 170));
            this.btnConsultas.setColorPressed(new Color(142, 36, 170));

            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));
            
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));

            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));

            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));

            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));

            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(74, 20, 140));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));
        }


    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnPedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidosMousePressed
        
        this.btnInicio.setSelected(false);
        this.btnRegVenta.setSelected(false);
        this.btnProveedores.setSelected(false);
        this.btnInventario.setSelected(false);
        this.btnPedidos.setSelected(true);
        this.btnEmpleados.setSelected(false);
        this.btnSalir.setSelected(false);
        this.btnConsultas.setSelected(false);
        
        
    }//GEN-LAST:event_btnPedidosMousePressed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
        
         new CambiaPaneles(pnlPrincipal, new pnlPedidos());
        if (this.btnPedidos.isSelected()) {
            this.btnPedidos.setColorNormal(new Color(142, 36, 170));
            this.btnPedidos.setColorHover(new Color(142, 36, 170));
            this.btnPedidos.setColorPressed(new Color(142, 36, 170));
            
         
            this.btnConsultas.setColorNormal(new Color(106, 27, 154));
            this.btnConsultas.setColorHover(new Color(106, 27, 154));
            this.btnConsultas.setColorPressed(new Color(106, 27, 154));

            this.btnInventario.setColorNormal(new Color(106, 27, 154));
            this.btnInventario.setColorHover(new Color(74, 20, 140));
            this.btnInventario.setColorPressed(new Color(106, 27, 154));

            this.btnRegVenta.setColorNormal(new Color(106, 27, 154));
            this.btnRegVenta.setColorHover(new Color(74, 20, 140));
            this.btnRegVenta.setColorPressed(new Color(106, 27, 154));

            this.btnInicio.setColorNormal(new Color(106, 27, 154));
            this.btnInicio.setColorHover(new Color(74, 20, 140));
            this.btnInicio.setColorPressed(new Color(106, 27, 154));

            this.btnProveedores.setColorNormal(new Color(106, 27, 154));
            this.btnProveedores.setColorHover(new Color(74, 20, 140));
            this.btnProveedores.setColorPressed(new Color(106, 27, 154));

            this.btnEmpleados.setColorNormal(new Color(106, 27, 154));
            this.btnEmpleados.setColorHover(new Color(74, 20, 140));
            this.btnEmpleados.setColorPressed(new Color(106, 27, 154));

            this.btnSalir.setColorNormal(new Color(106, 27, 154));
            this.btnSalir.setColorHover(new Color(74, 20, 140));
            this.btnSalir.setColorPressed(new Color(106, 27, 154));

        } else {
            this.btnPedidos.setColorNormal(new Color(106, 27, 154));
            this.btnPedidos.setColorHover(new Color(74, 20, 140));
            this.btnPedidos.setColorPressed(new Color(106, 27, 154));
        }
        
        
    }//GEN-LAST:event_btnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbutton.RSButton btnConsultas;
    private rsbutton.RSButton btnEmpleados;
    private rsbutton.RSButton btnInicio;
    private rsbutton.RSButton btnInventario;
    private javax.swing.JButton btnMenu1;
    private rsbutton.RSButton btnPedidos;
    private rsbutton.RSButton btnProveedores;
    private rsbutton.RSButton btnRegVenta;
    private rsbutton.RSButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private rsbutton.RSButton rSButton6;
    // End of variables declaration//GEN-END:variables
}
